CREATE TABLE IF NOT EXISTS characters (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  gender VARCHAR(16) NOT NULL DEFAULT '未知',
  birthplace VARCHAR(255) NULL,
  age INT NULL,
  height_cm INT NULL,
  weight_kg DECIMAL(6,2) NULL,
  skin_tone VARCHAR(100) NULL,
  hairstyle VARCHAR(255) NULL,
  clothing_style VARCHAR(255) NULL,
  intro TEXT NULL,
  tone VARCHAR(255) NULL,
  portraits INT NOT NULL DEFAULT 0,
  voices INT NOT NULL DEFAULT 0,
  videos INT NOT NULL DEFAULT 0,
  memories INT NOT NULL DEFAULT 0,
  assets_json LONGTEXT NULL,
  memories_json LONGTEXT NULL,
  thinking_model VARCHAR(32) NOT NULL DEFAULT 'preset',
  model_endpoint VARCHAR(1024) NULL,
  model_format LONGTEXT NULL,
  api_key VARCHAR(2048) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_characters_user_id (user_id),
  KEY idx_characters_gender (gender),
  KEY idx_characters_status (status),
  CONSTRAINT fk_characters_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);
